[project]
name = "redi-s26-lesson9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
redi-s26-lesson9 = "redi_s26_lesson9:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
